import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const STATIC_DIR = path.join(__dirname, '../emails/static');
const OUTPUT_FILE = path.join(__dirname, '../emails/assets/images.ts');

async function generateImages() {
  // Convert SVG to PNG and then to base64
  const headerPng = await sharp(path.join(STATIC_DIR, 'header.svg'))
    .resize(600, 200)
    .png()
    .toBuffer();

  const logoPng = await sharp(path.join(STATIC_DIR, 'logo.svg'))
    .resize(120, null, { fit: 'inside' })
    .png()
    .toBuffer();

  const headerBase64 = `data:image/png;base64,${headerPng.toString('base64')}`;
  const logoBase64 = `data:image/png;base64,${logoPng.toString('base64')}`;

  // Generate the constants file
  const output = `// Auto-generated file - do not edit manually
// Generated by: bun run scripts/generate-image-constants.ts

export const HEADER_IMAGE = '${headerBase64}';

export const LOGO_IMAGE = '${logoBase64}';
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output);

  console.log('Generated image constants at:', OUTPUT_FILE);
  console.log(
    'Header image size:',
    Math.round(headerBase64.length / 1024),
    'KB',
  );
  console.log('Logo image size:', Math.round(logoBase64.length / 1024), 'KB');
}

generateImages().catch(console.error);
